# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Multisensor-Datensatz mit ungewöhnlichen Objekten für autonomes Fahren
description: >- # this means to ignore newlines until "baseurl:"
  Die Mathematische Modellierung von industriellen Lebenszyklen Arbeitsgruppe des Mathematik Instituts der TU Berlin arbeitet an einem Multisensor-Datensatz mit ungewöhnlichen Objekten für autonomes Fahren, der öffentlich zugänglich gemacht wird, um die Forschung und Industrie in Deutschland und weltweit voranzutreiben. Dieser Datensatz wird es Forschern und Entwicklern ermöglichen, ihre Algorithmen unter realen Bedingungen zu testen und zu verbessern, was zu sichereren und zuverlässigeren autonomen Fahrsystemen führen wird.
baseurl: "" # the subpath of your site, e.g. /blog
google-site-verification: AOKtwPHPHAN41zhNGYi5f2aZlaZMVAA1p1OtD08XXIo
navigation:
    - title: Home
      url: ""
    - title: Sensoren
      url: sensoren
    - title: Anonymisierung
      url: anonymisierung
    - title: Veröffentlichung
      url: veroeffentlichung
    - title: Daten
      url: daten

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
    - jekyll-remote-theme
    - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
